# Generated by Django 5.1.1 on 2024-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iduser',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentorado', 'Mentorado')], default='Mentorado', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('iduser', 'gmail', 'cpf')},
        ),
    ]
